### ISSUE TITLE
Network issues with Alpine Linux

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-cli#212]
Hello.

I have not always, but often, stuck (3+ minutes) `cirrus` CLI at this moment:

```
apk add --no-cache git
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
```

What a problem can be here? Image is `alpine:3`. I saw answers about [Docker `--network` flag](https://docs.docker.com/network/host/), but I didn't find such flag for `cirrus` CLI.

```
> sudo cirrus --version
cirrus version 0.23.1-unknown
```

**Comment by fkorotkov** [comment]
Where did you see that --network flag can help? 🤔

**Comment by AlexWayfer** [comment]
> Where did you see that --network flag can help?

Like here: https://stackoverflow.com/a/54003007/2630849

But it seems like a problem with my WireGuard personal VPN. 😞  I'm going to close it for now.

**Comment by AlexWayfer** [comment]
The similar problem with `docker` command, with different hosts (sources), but `network=host` seems helping. I guess, it can be a feature request, can't it?

**Comment by edigaryev** [comment]
> The similar problem with `docker` command, with different hosts (sources), but `network=host` seems helping.

I don't quite understand what you mean by "different hosts" and "sources"? Can you explain this setup a little bit more?

Or, even better, perhaps you have a minimally reproducible example?

**Comment by AlexWayfer** [comment]
> I don't quite understand what you mean by "different hosts" and "sources"? Can you explain this setup a little bit more?

Of course: I mean different… sources for downloading. In the description of this issue I've mentioned `http://dl-cdn.alpinelinux.org`, but I also had (phantom, occasional) problems with `rubygems.org`, `github.com`, something else.



> Or, even better, perhaps you have a minimally reproducible example?

I'm working on https://github.com/AlexWayfer/stream_timer/pull/12 and was trying https://github.com/AlexWayfer/stream_timer/pull/34.

**Comment by edigaryev** [comment]
I tried building the following `.cirrus.yml` in a loop using `while true;do cirrus run -o simple -v;done`:

```yaml
container:
  image: alpine:3

task:
  script: apk add --no-cache bash git
```

...and it seems to be running stable without hangs for a few minutes.

I wonder if this depends on the external network conditions and adding `--net=host` solves the issue by the virtue of simply re-running a Docker command.

Assuming I've minimized the test-case correctly, can you try reproducing this on your machine?

**Comment by AlexWayfer** [comment]
@edigaryev did you read my comment about WireGuard above? With disabled WG service **or** with `--network=host` everything seems OK.

**Comment by edigaryev** [comment]
> @edigaryev did you read my comment about WireGuard above? With disabled WG service **or** with `--network=host` everything seems OK.

Got it, this only manifests itself with the VPN turned on.

In case your VPN's network overlaps with the Docker one, you can tell the Docker daemon to use a different network subnet instead of the default one (I think it's `172.17.0.0/16`): https://support.getjoan.com/hc/en-us/articles/360008889859-How-to-change-the-Docker-default-subnet-IP-address.

**Comment by AlexWayfer** [comment]
> In case your VPN's network overlaps with the Docker one, you can tell the Docker daemon to use a different network subnet instead of the default one (I think it's `172.17.0.0/16`): https://support.getjoan.com/hc/en-us/articles/360008889859-How-to-change-the-Docker-default-subnet-IP-address.

Thank you, but it didn't help. What about IPv6?

I have such WireGuard config:

```
> sudo cat /etc/wireguard/wg0.conf
[Interface]
Address = 10.8.0.2/24, fd00:8::2/48
```

And I've tried such Docker config:

```
> sudo cat /etc/docker/daemon.json
{
	"default-address-pools": [
		{
			"base": "10.8.0.0/16",
			"size": 24
		},
		{
			"base": "2a01:4f9:c010:45ec::/64",
			"size": 96
		}
	]
}
```

and I'm getting such errors:

```
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: fatal error: runtime: out of memory
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: runtime stack:
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: runtime.throw(0x56373e0c0e9f, 0x16)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         runtime/panic.go:1116 +0x74
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: runtime.sysMap(0xc004000000, 0x800000000, 0x56373fa8cdb8)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         runtime/mem_linux.go:169 +0xc7
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: runtime.(*mheap).sysAlloc(0x56373fa70240, 0x800000000, 0x56373c4d07d7, 0x56373fa70248)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         runtime/malloc.go:727 +0x1d4
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: runtime.(*mheap).grow(0x56373fa70240, 0x400000, 0x0)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         runtime/mheap.go:1344 +0x85
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: runtime.(*mheap).allocSpan(0x56373fa70240, 0x400000, 0x7f3b8b7f0000, 0x56373fa8cdc8, 0x7f3b8b7fdca8)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         runtime/mheap.go:1160 +0x6b6
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: runtime.(*mheap).alloc.func1()
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         runtime/mheap.go:907 +0x66
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: runtime.(*mheap).alloc(0x56373fa70240, 0x400000, 0x7f3ba8c30100, 0x7f3b8b7fdd30)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         runtime/mheap.go:901 +0x85
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: runtime.largeAlloc(0x800000000, 0x7f3b8b7f0001, 0x56373c50a190)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         runtime/malloc.go:1177 +0x94
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: runtime.mallocgc.func1()
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         runtime/malloc.go:1071 +0x48
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: runtime.systemstack(0x7f3b7c000020)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         runtime/asm_amd64.s:370 +0x63
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: runtime.mstart()
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         runtime/proc.go:1116
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: goroutine 1 [running]:
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: runtime.systemstack_switch()
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         runtime/asm_amd64.s:330 fp=0xc000a60818 sp=0xc000a60810 pc=0x56373c513b40
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: runtime.mallocgc(0x800000000, 0x56373e6a4720, 0xc000a16d01, 0x10)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         runtime/malloc.go:1070 +0x958 fp=0xc000a608b8 sp=0xc000a60818 pc=0x56373c4b24d8
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: runtime.makeslice(0x56373e6a4720, 0x0, 0x100000000, 0x10)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         runtime/slice.go:98 +0x6e fp=0xc000a608e8 sp=0xc000a608b8 pc=0x56373c4f3c6e
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils.splitNetwork(0x60, 0xc00189d7d0, 0x10, 0x40, 0x10)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils/utils.go:114 +0xfd fp=0xc000a609b8 sp=0xc000a608e8 pc=0x56373cf73d7d
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils.splitNetworks(0xc000a8cfc0, 0x2, 0x4, 0x56373e0aa662, 0xd, 0xc000ba02e0, 0x18, 0xc0004c2200)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils/utils.go:104 +0x193 fp=0xc000a60a90 sp=0xc000a609b8 pc=0x56373cf739f3
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils.configDefaultNetworks(0xc000a8cfc0, 0x2, 0x4, 0x56373fa4db90, 0x0, 0x0)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils/utils.go:51 +0x97 fp=0xc000a60af8 sp=0xc000a60a90 pc=0x56373cf73597
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils.ConfigLocalScopeDefaultNetworks(...)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils/utils.go:88
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: github.com/docker/docker/vendor/github.com/docker/libnetwork/ipams/builtin.Init(0x56373ea605a0, 0xc001926540, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc001926500)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         github.com/docker/docker/vendor/github.com/docker/libnetwork/ipams/builtin/builtin_unix.go:38 +0x19f fp=0xc000a60b70 sp=0xc000a60af8 pc=0x56373d366f3f
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: github.com/docker/docker/vendor/github.com/docker/libnetwork.initIPAMDrivers(0xc001926540, 0x0, 0x0, 0x0, 0x0, 0xc000a8cfc0, 0x2, 0x4, 0x18f, 0x190)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers_ipam.go:19 +0xfe fp=0xc000a60be0 sp=0xc000a60b70 pc=0x56373d3eed3e
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: github.com/docker/docker/vendor/github.com/docker/libnetwork.New(0xc0005b7a80, 0xa, 0x10, 0xc000a0e900, 0xc0006caea0, 0xc0005b7a80, 0xa)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:226 +0x668 fp=0xc000a60d90 sp=0xc000a60be0 pc=0x56373d3e4e28
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc00000c1e0, 0xc000157080, 0xc0006caea0, 0xc0004fa3c0, 0xc00000c1e0, 0xc000f4bf50, 0xc0006caea0)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         github.com/docker/docker/daemon/daemon_unix.go:855 +0xa9 fp=0xc000a60e48 sp=0xc000a60d90 pc=0x56373dcf66c9
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: github.com/docker/docker/daemon.(*Daemon).restore(0xc00000c1e0, 0xc000aa2380, 0xc0004ce000)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         github.com/docker/docker/daemon/daemon.go:490 +0x52c fp=0xc000a61040 sp=0xc000a60e48 pc=0x56373dce5dac
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: github.com/docker/docker/daemon.NewDaemon(0x56373ea7cb20, 0xc000aa2380, 0xc000157080, 0xc000a0e900, 0x0, 0x0, 0x0)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         github.com/docker/docker/daemon/daemon.go:1143 +0x2bbc fp=0xc000a61998 sp=0xc000a61040 pc=0x56373dce9dbc
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: main.(*DaemonCli).start(0xc000d5ba40, 0xc00032c7e0, 0x0, 0x0)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         github.com/docker/docker/cmd/dockerd/daemon.go:195 +0x756 fp=0xc000a61d30 sp=0xc000a61998 pc=0x56373e08c8d6
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: main.runDaemon(...)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         github.com/docker/docker/cmd/dockerd/docker_unix.go:13
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: main.newDaemonCommand.func1(0xc0001c0840, 0xc000a8c800, 0x0, 0x2, 0x0, 0x0)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         github.com/docker/docker/cmd/dockerd/docker.go:34 +0x7d fp=0xc000a61d68 sp=0xc000a61d30 pc=0x56373e09503d
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc0001c0840, 0xc00004e190, 0x2, 0x2, 0xc0001c0840, 0xc00004e190)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:850 +0x47c fp=0xc000a61e40 sp=0xc000a61d68 pc=0x56373e07ad3c
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0001c0840, 0x0, 0x0, 0x10)
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]:         github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:958 +0x375 fp=0xc000a61f18 sp=0xc000a61e40 pc=0x56373e07b8b5
Jan 13 04:08:16 Alex-ArchMainPC dockerd[23269]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(...)

...
```

or with `fd00:8::2/48`:

```
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: fatal error: runtime: out of memory
Jan 13 04:08:14 Alex-ArchMainPC kernel: audit: type=1325 audit(1610500094.667:644): table=filter family=2 entries=34 op=xt_replace pid=23267 comm="iptables"
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: runtime stack:
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: runtime.throw(0x55c1e5827e9f, 0x16)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         runtime/panic.go:1116 +0x74
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: runtime.sysMap(0xc004000000, 0x800000000, 0x55c1e71f3db8)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         runtime/mem_linux.go:169 +0xc7
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: runtime.(*mheap).sysAlloc(0x55c1e71d7240, 0x800000000, 0x55c1e3c377d7, 0x55c1e71d7248)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         runtime/malloc.go:727 +0x1d4
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: runtime.(*mheap).grow(0x55c1e71d7240, 0x400000, 0x0)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         runtime/mheap.go:1344 +0x85
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: runtime.(*mheap).allocSpan(0x55c1e71d7240, 0x400000, 0x0, 0x55c1e71f3dc8, 0x7f822f7f5ca8)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         runtime/mheap.go:1160 +0x6b6
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: runtime.(*mheap).alloc.func1()
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         runtime/mheap.go:907 +0x66
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: runtime.(*mheap).alloc(0x55c1e71d7240, 0x400000, 0x7f83ec2d0100, 0x7f822f7f5d30)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         runtime/mheap.go:901 +0x85
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: runtime.largeAlloc(0x800000000, 0x7f822f7f0001, 0x55c1e3c71190)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         runtime/malloc.go:1177 +0x94
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: runtime.mallocgc.func1()
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         runtime/malloc.go:1071 +0x48
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: runtime.systemstack(0x7f8290000020)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         runtime/asm_amd64.s:370 +0x63
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: runtime.mstart()
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         runtime/proc.go:1116
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: goroutine 1 [running]:
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: runtime.systemstack_switch()
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         runtime/asm_amd64.s:330 fp=0xc00161e818 sp=0xc00161e810 pc=0x55c1e3c7ab40
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: runtime.mallocgc(0x800000000, 0x55c1e5e0b720, 0xc00017d501, 0x10)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         runtime/malloc.go:1070 +0x958 fp=0xc00161e8b8 sp=0xc00161e818 pc=0x55c1e3c194d8
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: runtime.makeslice(0x55c1e5e0b720, 0x0, 0x100000000, 0x10)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         runtime/slice.go:98 +0x6e fp=0xc00161e8e8 sp=0xc00161e8b8 pc=0x55c1e3c5ac6e
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils.splitNetwork(0x60, 0xc0013d4450, 0x10, 0x40, 0x10)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils/utils.go:114 +0xfd fp=0xc00161e9b8 sp=0xc00161e8e8 pc=0x55c1e46dad7d
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils.splitNetworks(0xc000200160, 0x2, 0x4, 0x55c1e5811662, 0xd, 0xc000d826a0, 0x18, 0xc000218200)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils/utils.go:104 +0x193 fp=0xc00161ea90 sp=0xc00161e9b8 pc=0x55c1e46da9f3
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils.configDefaultNetworks(0xc000200160, 0x2, 0x4, 0x55c1e71b4b90, 0x0, 0x0)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils/utils.go:51 +0x97 fp=0xc00161eaf8 sp=0xc00161ea90 pc=0x55c1e46da597
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils.ConfigLocalScopeDefaultNetworks(...)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils/utils.go:88
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: github.com/docker/docker/vendor/github.com/docker/libnetwork/ipams/builtin.Init(0x55c1e61c75a0, 0xc000ea4600, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc000ea45c0)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         github.com/docker/docker/vendor/github.com/docker/libnetwork/ipams/builtin/builtin_unix.go:38 +0x19f fp=0xc00161eb70 sp=0xc00161eaf8 pc=0x55c1e4acdf3f
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: github.com/docker/docker/vendor/github.com/docker/libnetwork.initIPAMDrivers(0xc000ea4600, 0x0, 0x0, 0x0, 0x0, 0xc000200160, 0x2, 0x4, 0x55c1e5e43060, 0x55c1e5e43201)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers_ipam.go:19 +0xfe fp=0xc00161ebe0 sp=0xc00161eb70 pc=0x55c1e4b55d3e
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: github.com/docker/docker/vendor/github.com/docker/libnetwork.New(0xc00011ec80, 0xa, 0x10, 0xc0004b0cf0, 0xc000b10d50, 0xc00011ec80, 0xa)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:226 +0x668 fp=0xc00161ed90 sp=0xc00161ebe0 pc=0x55c1e4b4be28
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc00000c1e0, 0xc00021db80, 0xc000b10d50, 0xc000442280, 0xc00000c1e0, 0xc0004b2a90, 0xc000b10d50)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         github.com/docker/docker/daemon/daemon_unix.go:855 +0xa9 fp=0xc00161ee48 sp=0xc00161ed90 pc=0x55c1e545d6c9
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: github.com/docker/docker/daemon.(*Daemon).restore(0xc00000c1e0, 0xc000215200, 0xc0004ea000)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         github.com/docker/docker/daemon/daemon.go:490 +0x52c fp=0xc00161f040 sp=0xc00161ee48 pc=0x55c1e544cdac
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: github.com/docker/docker/daemon.NewDaemon(0x55c1e61e3b20, 0xc000215200, 0xc00021db80, 0xc0004b0cf0, 0x0, 0x0, 0x0)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         github.com/docker/docker/daemon/daemon.go:1143 +0x2bbc fp=0xc00161f998 sp=0xc00161f040 pc=0x55c1e5450dbc
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: main.(*DaemonCli).start(0xc00093f650, 0xc0001694a0, 0x0, 0x0)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         github.com/docker/docker/cmd/dockerd/daemon.go:195 +0x756 fp=0xc00161fd30 sp=0xc00161f998 pc=0x55c1e57f38d6
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: main.runDaemon(...)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         github.com/docker/docker/cmd/dockerd/docker_unix.go:13
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: main.newDaemonCommand.func1(0xc000467600, 0xc0001113c0, 0x0, 0x2, 0x0, 0x0)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         github.com/docker/docker/cmd/dockerd/docker.go:34 +0x7d fp=0xc00161fd68 sp=0xc00161fd30 pc=0x55c1e57fc03d
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc000467600, 0xc00004e190, 0x2, 0x2, 0xc000467600, 0xc00004e190)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:850 +0x47c fp=0xc00161fe40 sp=0xc00161fd68 pc=0x55c1e57e1d3c
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000467600, 0x0, 0x0, 0x10)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:958 +0x375 fp=0xc00161ff18 sp=0xc00161fe40 pc=0x55c1e57e28b5
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:895
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: main.main()
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         github.com/docker/docker/cmd/dockerd/docker.go:97 +0x17d fp=0xc00161ff88 sp=0xc00161ff18 pc=0x55c1e57fadfd
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: runtime.main()
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         runtime/proc.go:204 +0x209 fp=0xc00161ffe0 sp=0xc00161ff88 pc=0x55c1e3c458c9
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]: runtime.goexit()
Jan 13 04:08:14 Alex-ArchMainPC dockerd[23033]:         runtime/asm_amd64.s:1374 +0x1 fp=0xc00161ffe8 sp=0xc00161ffe0 pc=0x55c1e3c7c901

...
```

**Comment by edigaryev** [comment]
>Thank you, but it didn't help.

I don't think it would, since you've configured two overlapping networks:

* `10.8.0.2/24` (WireGuard)
* `10.8.0.0/16` (Docker)

Try `10.9.0.0/16` for Docker instead (or `10.9.0.0/16` for WireGuard).

>fatal error: runtime: out of memory

That's interesting, but looks like a system/Docker daemon related issue. Are you running out of memory?
